# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def basicFrameworks
  
  pod 'Moya/RxSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  
end

def designFrameworks
  
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 6.0'
  pod 'Then'
  
end

target 'SearchingBlogAndCafe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for SearchingBlogAndCafe
  basicFrameworks
  
  designFrameworks
  
  target 'SearchingBlogAndCafeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SearchingBlogAndCafeUITests' do
    # Pods for testing
  end

end

target 'Network' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Network
  basicFrameworks
end
